title: HOSp
description: Health Open Space
theme: just-the-docs

url: https://healthopenspace.github.io/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
plugins:
  - jekyll-default-layout
  - jekyll-spaceship  

color_scheme: wider

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/hosp.svg"